-- Complemento para a feature de reserva de computadores de laboratorio.
-- O schema principal do grupo ja possui public.users, public.rooms,
-- public.reservations e public.maintenance_requests.
-- Rode este arquivo apenas se a tabela de reserva de computadores ainda nao existir.

do $$
begin
  create type computer_reservation_status as enum ('pending', 'confirmed', 'denied', 'completed');
exception
  when duplicate_object then null;
end $$;

create table if not exists equipment_reservations (
  id integer generated by default as identity primary key,
  user_cpf varchar not null,
  user_name varchar not null,
  room varchar not null,
  computer_quantity integer not null check (computer_quantity > 0),
  start_time timestamp without time zone not null,
  end_time timestamp without time zone not null,
  status computer_reservation_status not null default 'pending',
  constraint valid_computer_reservation_window check (end_time > start_time)
);

create index if not exists ix_equipment_reservations_user_cpf on equipment_reservations(user_cpf);
create index if not exists ix_equipment_reservations_room on equipment_reservations(room);
create index if not exists ix_equipment_reservations_start_time on equipment_reservations(start_time);
create index if not exists ix_equipment_reservations_end_time on equipment_reservations(end_time);
create index if not exists ix_equipment_reservations_status on equipment_reservations(status);
