-- Complemento para a feature de reserva de equipamentos.
-- O schema principal do grupo ja possui public.users, public.rooms,
-- public.reservations e public.maintenance_requests.
-- Rode este arquivo apenas se as tabelas de equipamento ainda nao existirem.

do $$
begin
  create type equipment_status as enum ('available', 'maintenance');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type equipment_reservation_status as enum ('Pending', 'In Use', 'Canceled');
exception
  when duplicate_object then null;
end $$;

create table if not exists equipment (
  id integer generated by default as identity primary key,
  name varchar(120) not null unique,
  status equipment_status not null default 'available',
  total_quantity integer not null default 0 check (total_quantity >= 0),
  description text
);

create table if not exists equipment_reservations (
  id integer generated by default as identity primary key,
  user_cpf varchar not null,
  user_name varchar not null,
  equipment_type varchar not null,
  quantity integer not null check (quantity > 0),
  pickup_time timestamptz not null,
  return_time timestamptz not null,
  status equipment_reservation_status not null default 'Pending',
  constraint valid_equipment_reservation_window check (return_time > pickup_time),
  constraint uq_equipment_reservation_user_exact_window unique (user_cpf, pickup_time, return_time)
);

create index if not exists ix_equipment_name on equipment(name);
create index if not exists ix_equipment_reservations_user_cpf on equipment_reservations(user_cpf);
create index if not exists ix_equipment_reservations_equipment_type on equipment_reservations(equipment_type);
create index if not exists ix_equipment_reservations_pickup_time on equipment_reservations(pickup_time);
create index if not exists ix_equipment_reservations_return_time on equipment_reservations(return_time);
create index if not exists ix_equipment_reservations_status on equipment_reservations(status);
